### ISSUE TITLE
/epochs/tags has incorrect type [fails validation]

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/nwb-api#2]
If I create a new nwb file using the following code (adapted from one of the examples)

```python

#!/usr/bin/python
import sys
import nwb
import numpy as np

from nwb.nwbco import *

def main():
    """
    Store extracellular ephys data

    """

    ########################################################################
    # create a new NWB file
    # several settings are specified when doing so. these can be supplied within
    #   the NWB constructor or defined in a dict, as in in this example
    settings = {}
    settings["filename"] = "sample_extracellular_ephys.nwb"

    # each file should have a descriptive globally unique identifier
    #   that specifies the lab and this experiment session
    # the function nwb.create_identifier() is recommended to use as it takes
    #   the string and appends the present date and time
    settings["identifier"] = nwb.create_identifier("extracellular ephys example")

    # indicate that it's OK to overwrite exting file
    # settings["modify"] = True
    settings["overwrite"] = True

    # specify the start time of the experiment. all times in the NWB file
    #   are relative to experiment start time
    # if the start time is not specified the present time will be used
    settings["start_time"] = "Sat Jul 04 2015 3:14:16"

    # provide one or two sentences that describe the experiment and what
    #   data is in the file
    settings["description"] = "Test file demonstrating a simple extracellular ephys recording"

    # create the NWB object. this manages the file
    print "Creating " + settings["filename"]
    neurodata = nwb.NWB(**settings)

    # close file, otherwise it will fail to write properly
    neurodata.close()

if __name__ == '__main__':
    main()
```

the so created NWB file does not validate against api-python 52e97e76 (update matlab_unittest run_all_tests to work with matlab_r2017a by replacing run with feval, 2017-06-18).

The validation log is:
```
$ python -m nwb.nwb_validate sample_extracellular_ephys.nwb - /h/projekte/api-python/nwb/nwb_core.py
Reading 11 groups and 5 datasets

******
Validation messages follow.
** one error.
1 Miscellaneous errors:
  1. '/epochs': autogen attribute [tags] values incorrect.
     expected:[] (type <type 'numpy.ndarray', dtype='|S1'>)
     found:[] (type <type 'str'>)
No groups missing. -- Good
No datasets missing. -- Good
No attributes missing. -- Good
No Incorrect attribute values. -- Good
No groups custom missing attribute neurodata_type=Custom. -- Good
No datasets custom missing attribute neurodata_type=Custom. -- Good
No groups defined in extension, but missing attribute schema_id. -- Good
No datasets defined in extension, but missing attribute schema_id. -- Good
** 5 warnings.
No Miscellaneous warnings. -- Good
No groups custom inside custom missing attribute neurodata_type=Custom. -- Good
No datasets custom inside custom missing attribute neurodata_type=Custom. -- Good
No recommended groups missing. -- Good
5 recommended datasets missing:
  1. '/general/experiment_description'
  2. '/general/experimenter'
  3. '/general/institution'
  4. '/general/lab'
  5. '/general/session_id'
No recommended attributes missing. -- Good
No recommended attributes empty. -- Good
No required_attributes_empty. -- Good
No added attributes not described by extension. -- Good
** No additions.
No groups custom and identified by attribute neurodata_type=Custom.
No datasets custom and identified by attribute neurodata_type=Custom.
No groups defined by extension and identified by attribute schema_id.
No datasets defined by extension and identified by attribute schema_id.
No added attributes described by extension.
** Summary
1 errors, 5 warnings, 0 additions
failed validation check (at least one error)
```

**Comment by keithg-alleninstitute** [comment]
Hi Thomas,


Though the example script that you derived your example from indeed does not validate, the script you sent below seems to validate against the NWB version that the Allen is supporting, which iirc is 1.0.5x (where x='c'?).

Off the top of my head I can't say the source of the validation error. If what you're encountering is an problem for you then we'll have to bump this up the administrative ladder and get clearance to fix our API to support a newer NWB version.

Let me know what you think.

All the best,
Keith


Validation messages follow.
** No errors. -- Good
No Miscellaneous errors. -- Good
No groups missing. -- Good
No datasets missing. -- Good
No attributes missing. -- Good
No Incorrect attribute values. -- Good
No groups custom missing attribute neurodata_type=Custom. -- Good
No datasets custom missing attribute neurodata_type=Custom. -- Good
No groups defined in extension, but missing attribute schema_id. -- Good
No datasets defined in extension, but missing attribute schema_id. -- Good
** 5 warnings.
No Miscellaneous warnings. -- Good
No groups custom inside custom missing attribute neurodata_type=Custom. -- Good
No datasets custom inside custom missing attribute neurodata_type=Custom. -- Good
No recommended groups missing. -- Good
5 recommended datasets missing:
  1. '/general/experiment_description'
  2. '/general/experimenter'
  3. '/general/institution'
  4. '/general/lab'
  5. '/general/session_id'
No recommended attributes missing. -- Good
No recommended attributes empty. -- Good
No required_attributes_empty. -- Good
No added attributes not described by extension. -- Good
** No additions.
No groups custom and identifieed by attribute neurodata_type=Custom.
No datasets custom and identifieed by attribute neurodata_type=Custom.
No groups defined by extension and identified by attribute schema_id.
No datasets defined by extension and identified by attribute schema_id.
No added attributes described by extension.
** Summary
0 errors, 5 warnings, 0 additions
passed validation check (no errors)



________________________________

**Comment by t-b** [comment]
@keithg-alleninstitute Thanks for the quick reply.

What is the authorative NWB specification document the Allen Institute is using? I also want to follow that specification. The document in this repo here seems outdated.

The violation is that "/epochs/tags" is created as a string by ai-nwb. And all specification versions I have found say that this should be a text array.

**Comment by t-b** [comment]
Sample file: byte-physics.de/Downloads/sample_extracellular_ephys.nwb

**Comment by keithg-alleninstitute** [comment]
Hi Thomas,

That's a great question, and probably best suited to Rob (CC'd), who was PM on the project. Control of the specification was passed on to external entities and we stopped documenting internally, so I have nothing definitive to offer.  ‎We committed to version 1.0.5, which was supposed to be locked down and not developed further. Unfortunately, development continued, but that's another story. Rob should have better input on where to get the official spec that we support.

All the best,
Keith



From: Thomas Braun
Sent: Friday, June 23, 2017 09:15
To: AllenInstitute/nwb-api
Reply To: AllenInstitute/nwb-api
Cc: Keith Godfrey; Mention
Subject: Re: [AllenInstitute/nwb-api] /epochs/tags has incorrect type [fails validation] (#2)



@keithg-alleninstitute<https://github.com/keithg-alleninstitute> Thanks for the quick reply.

What is the authorative NWB specification document the Allen Institute is using? I also want to follow that specification. The document in this repo here seems outdated.

The violation is that "/epochs/tags" is created as a string by ai-nwb. And all specification versions I have found say that this should be a text array.

**Comment by keithg-alleninstitute** [comment]
Whoops, wrong cc

**Comment by keithg-alleninstitute** [comment]
Hi Thomas,

The Allen Institute committed to version 1.05 of the NWB specification. To my knowledge, this is the spec our developers implemented:

https://github.com/NeurodataWithoutBorders/specification/tree/master/version_1.0.5_beta

Keith, could you confirm that this is the version of the spec you referenced? I can only comment on the official party line. :)

Have a good weekend,
Rob

**Comment by keithg-alleninstitute** [comment]
Thank you Rob.


Thomas -- I believe that the "1.0.5_beta" documentation at the link below represents what we use, although I cannot be sure as there were several "1.0.5" versions. Do not use the "1.0.5g_beta" -- that is certainly incorrect.


Also, I'll investigate the epoch tag issue on our side and make sure that we're running the appropriate validator. Thank you for pointing out that there's a potential validation issue.


By the way, would you know what commit 52e97e76 corresponds to? I can research it but I thought I'd ask first.


Have a great weekend,

Keith


________________________________
From: Rob Young
Sent: Friday, June 23, 2017 2:31 PM
To: Keith Godfrey; Thomas Braun
Subject: RE: [AllenInstitute/nwb-api] /epochs/tags has incorrect type [fails validation] (#2)


Hi Thomas,



The Allen Institute committed to version 1.05 of the NWB specification. To my knowledge, this is the spec our developers implemented:



https://github.com/NeurodataWithoutBorders/specification/tree/master/version_1.0.5_beta

[https://avatars0.githubusercontent.com/u/12140348?v=3&s=400]<https://github.com/NeurodataWithoutBorders/specification/tree/master/version_1.0.5_beta>

NeurodataWithoutBorders/specification - GitHub<https://github.com/NeurodataWithoutBorders/specification/tree/master/version_1.0.5_beta>
github.com
NWB format specification and schema. ... Failed to load latest commit information. NWB_file_format_specification_1.0.5g_beta.html




Keith, could you confirm that this is the version of the spec you referenced? I can only comment on the official party line. :)



Have a good weekend,

Rob

**Comment by t-b** [comment]
@keithg-alleninstitute 

Thanks for the clarification. I've included the link into our igor pro module for writing NWB.

> By the way, would you know what commit 52e97e76 corresponds to? I can research it but I thought I'd ask first.

This is currently the latest commit in the api-nwb project, see NeurodataWithoutBorders/api-python@52e97e76. I thought I describe it like that instead of saying "the latest version" which will be ambiguous in a couple of months.
